name: Operational_sql_dbpatcher_eu
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  container-dbpatcher-job:
    runs-on: ubuntu-latest
    container:
      image: postgres:15 # Using the public PostgreSQL image

    steps:
    - name: Test database connection
      run: |
        echo "Testing database connection";
        PGPASSWORD="root" psql -U bob -p 5432 -d dvdrental -h 35.188.139.128 -c "SELECT now();";
        PGPASSWORD="root" psql -U bob -p 5432 -d dvdrental -h 35.188.139.128 -c "SELECT * FROM demo_table;";
